export const ApiUrl = Object.freeze({
  LOGIN: "/api/user/login",
  NAVER_LOGIN: "/api/naver/login",
  REGISTER: "/api/user/register",
  TEMPORARY_PASSWORD: "/api/user/random-password",
  ADMIN_USER_INFORMATION: "/api/users/admin",
  EMAIL_DOUBLE_CHECK: "/api/user/emailCheck",
  USER_INFORMATION: "/api/user/auth",
  CATEGORY: "/api/category",
  ADMIN_CATEGORY: "/api/category/admin",
  IMAGE: "/api/image",
  ADMIN_PRODUCTS: "/api/products/admin",
  PRODUCTS: "/api/products",
  PRODUCTS_OVERALL_INFORMATION: "/api/products?page=",
  PRODUCTS_FILTER: "/api/products/filter-search?key=",
  ORDERS: "/api/orders",
  USER_ORDERS: "/api/orders/auth",
  ADMIN_ORDERS: "/api/orders/admin",
  CART: "/api/cart/auth",
  COMMENTS: "/api/comments",
  AUTH_COMMENTS: "/api/comments/auth",
  ADMIN_COMMENTS: "/api/comments/admin",
});
